# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-21 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='goods_name',
            field=models.CharField(max_length=20, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(verbose_name='产品状态，0不正常1正常'),
        ),
    ]
