# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-21 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20180821_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='goods_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(),
        ),
    ]
