# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-21 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20180821_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=30)),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('task_describe', models.TextField(max_length=300)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Edition')),
            ],
        ),
    ]
