# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-21 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='task',
        ),
    ]
