# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-21 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20180821_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(default=1),
        ),
    ]
