# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-22 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20180822_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lastTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
