# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-22 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_lasttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='goods_name',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_describe',
            field=models.TextField(default='', max_length=300, verbose_name='项目描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_name',
            field=models.CharField(default='', max_length=20, verbose_name='项目名称'),
        ),
    ]
