# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-23 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20180822_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='person',
            name='modify_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(verbose_name='状态'),
        ),
    ]
