# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-23 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='environment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
