# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-23 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_task_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='environment',
        ),
    ]
