# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-23 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_remove_task_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edt', to='task.Edition'),
        ),
    ]
