# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-24 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_auto_20180824_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='modify_time',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
    ]
